### ISSUE TITLE
inline comments in config file

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/openmm-cmd#10]
```
$ python ~/projects/openmm-cmd/openmm --config config.ini
[OpenMM] ERROR | The 'traj_freq' trait of the simulation section instance must be an int, but a value of '1000  # 2 picoseconds' <type 'str'> was specified.

To see all available configurables, use `--help-all`
```

**Comment by rmcgibbo** [comment]
the comment should be filtered out before the typechecking/casting to int.

**Comment by leeping** [comment]
Hi Robert,

I found this problem as well.  It seems the ConfigParser from the Python Standard Library should be taking care of the comments, do you know why it's not?

**Comment by rmcgibbo** [comment]
For some reason the stdlib doesn't do this. But its fixed now.
