### ISSUE TITLE
context.setParameter() error when reading from restart file

### ISSUE THREAD

**Issue by leeping** [rmcgibbo/openmm-cmd#15]
Hi Robert,

It seems the Simulation object does not like it when we try to set the "MonteCarloPressure" context parameter.  Everything else works.  Do you know what might be the cause?
- Lee-Ping

**Comment by rmcgibbo** [comment]
The issue was that json was loading the context parameter names as unicode strings, and OpenMM wants them as byte strings (ascii). It's fixed now.
