### ISSUE TITLE
json restart file should probably be compressed

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/openmm-cmd#18]
gz/bz2 are both included within python.

**Comment by leeping** [comment]
Sure, we just need to ensure that it can read both uncompressed and compressed (since the user might decompress it).

**Comment by leeping** [comment]
Take a look at a458cddb016acc2b6cc694e9cdf921e87c4bde32 .

**Comment by rmcgibbo** [comment]
+1.
