### ISSUE TITLE
System validation could really benefit from knowing the force field.

### ISSUE THREAD

**Issue by leeping** [rmcgibbo/openmm-cmd#5]
For example, here is what happens if we are using the AMOEBA force field: 
- vdwCutoff becomes a valid option
- If periodic boundary conditions are on, we must use PME
- pme_grid and aewald become valid options but only if both of them are specified

Do you think there's a good way to handle this?

Thanks,
- Lee-Ping

**Comment by rmcgibbo** [comment]
right now `OpenMM.validate` is called during `initialize` on line 510. Maybe we could just call it later -- during `start`, and catch the trait error their?

**Comment by leeping** [comment]
I think that's a good idea.  I didn't know it was allowed to do this, but I can move it there. :)
- Lee-Ping

**Comment by rmcgibbo** [comment]
THERE ARE NO RULES :)

-Robert
