### ISSUE TITLE
We should be ready for a beta test.

### ISSUE THREAD

**Issue by leeping** [rmcgibbo/openmm-cmd#7]
Hi Robert,

I added nine example calculations along with instructions on how to run them.  I think the script should be ready for a public beta test now, but testers need to have the most recent development build of OpenMM.

Thanks,
- Lee-Ping

**Comment by rmcgibbo** [comment]
This is awesome. All the amoeba and xml options look great.

**Comment by rmcgibbo** [comment]
Do you know off the top of your head what the features are that require the dev. build? One of them is obviously the pickle restart reporter, but if we switch to JSON that will be solved.

**Comment by leeping** [comment]
The anisotropic barostat is another one.
- Lee-Ping

**Comment by rmcgibbo** [comment]
Okay. I'll tag a release and write up something that can be sent out on email/forums. 

-Robert

**Comment by leeping** [comment]
Hi Robert,

You can remove the anisotropic barostat from the examples if you want (or add a note in About.txt).  I imagine all the other examples should work with OpenMM 5.1 .

Thanks,
- Lee-Ping

**Comment by rmcgibbo** [comment]
Maybe we can do a version check inside the script? I'll install the 5.1 release version and make sure all the examples run with it or give an informative error saying why they don't run.

**Comment by leeping** [comment]
Sure, I think that's a good way to go. :)
- Lee-Ping

**Comment by leeping** [comment]
Also, feel free to switch to json if you want, which should enable the "restart" example for 5.1 users.  It should be as simple as "import json as pickle", although that might be misleading for readers of the code. :)

**Comment by rmcgibbo** [comment]
Yeah, I think switching to json is probably a good move for robustness and cross platform type stuff. But -1 on import json as pickle :)

-Robert
