### ISSUE TITLE
Remaining issues before 0.1-beta

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/openmm-cmd#8]
1. Run OpenMM version check. Only versions >=5.1 are supported, but some 5.2-dev features are exposed by the script that won't work with 5.1, like the anisotropic barostat. error out elegantly in this case.
2. Try to run all of the examples under the 5.1 release version as a test.
3. Rewrite the readme in a more concise format.
4. Create a tarball release, and perhaps also post it on pypi so people can pip install it (the easier this code is to get/install, the more likely we are to get some users to actually test it).
5. Send email to peter to post on the OpenMM forums and stuff, advertizing the beta test.
   6 ...
6. Profit.

**Comment by leeping** [comment]
These sound good.  Would you like me to do some of these, or are you planning to do it?
- Lee-Ping

**Comment by rmcgibbo** [comment]
Do you want to write up the readme?  I can do the rest.

**Comment by leeping** [comment]
Sure, I'll do it.
- Lee-Ping

**Comment by leeping** [comment]
I uploaded the new readme, let me know what you think (I didn't replace the old one, it's a new file.)
